### ISSUE TITLE
Setup.py doesn't run due to a minor error in script

### ISSUE THREAD

**Issue by torstees** [kids-first/kf-utils-python#19]
**Describe the bug**
line 25 says packages=setuptools.find_packages(),  but find_packages was imported, not the parent library

**To Reproduce**
It won't run as is, python complains about setuptools not having the function, find_packages()

**Expected behavior**
It should run without edit :)

**Computer (please complete the following information):**
WSL, but should fail on any platform

**Additional info**

**Comment by fiendish** [comment]
Thanks!
