### ISSUE TITLE
CI and unit testing

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-utils-python#21]
**Is your feature request related to a problem? Please describe.**
A lot of these functions are useful and I would like to use them in other production repos. However, there are no tests/CI setup so I'm apprehensive to do so. 

Also, I have a delete study method that I've written using kf-utils-python but it is living in study creator repo right now when it really should be living in this repo. Its in study creator bc we are able (or will be in the near future) test this function with a live dataservice to ensure it works. If this repo has CI and tests setup then I could move it here.

**Describe the solution you'd like**
Setup a CircleCI pipeline with the Data Service. Write unit tests for existing dataservice functionality

**Comment by fiendish** [comment]
Ok. I'll migrate over https://github.com/kids-first/kf-update-dbgap-consent/blob/master/.circleci/config.yml

**Comment by znatty22** [comment]
Thanks @fiendish!

**Comment by fiendish** [comment]
CI is set up now. No tests yet. Just uncomment the pytest invocation in the circle config if you add the first one.

**Comment by znatty22** [comment]
@fiendish I haven't worked with circleci in a while but if it can support custom images, then we could probably just use a dataservice image rather than build the whole app during CI setup. Plus I think with the way it is now we're always building the master branch which means we're always testing against QA rather than production

**Comment by fiendish** [comment]
> I haven't worked with circleci in a while but if it can support custom images, then we could probably just use a dataservice image

It can (https://circleci.com/docs/2.0/private-images/) but I'll leave that up to devops to worry about.

> Plus I think with the way it is now we're always building the master branch which means we're always testing against QA rather than production

That was a choice, but if you want to fetch @latest-release I don't have strong opinions about it.
